campaigns[9] = {
    name="Agents of S.H.I.E.L.D.",
    thumbnailUrl="https://steamusercontent-a.akamaihd.net/ugc/16941724884055868600/CBC30ED45FF773A8F3ADB914BA8AB2FF8555F72D/",
    imageUrl="",
    text={
        {
            text="Evidence",
            position={-78.00, 0.96, 16.00},
            color={1,1,1},
            fontSize=100
        },
        {
            text="S.H.I.E.L.D. Executive Board",
            position={-82.73, 0.96, -6.00},
            color={1,1,1},
            fontSize=88
        },
        {
            text="A.I.M\nInterference",
            position={-70.25, 0.96, -4.63},
            color={1,1,1},
            fontSize=88
        }
    },
    cards={
        {
            cardId="50181",
            position={-88.25, 0.51, -11.75},
            scale = Global.getTable("CARD_SCALE_ENCOUNTER")
        },
        {
            cardId="50182",
            position={-82.75, 0.51, -11.75},
            scale = Global.getTable("CARD_SCALE_ENCOUNTER")
        },
        {
            cardId="50183",
            position={-77.25, 0.51, -11.75},
            scale = Global.getTable("CARD_SCALE_ENCOUNTER")
        }
    },
    decks={
        {
            name="A.I.M. Interference",
            position={-70.25, 0.51, -11.75},
            scale=Global.getTable("CARD_SCALE_ENCOUNTER"),
            cards = {
                ["50184A"]=1,
                ["50184B"]=1,
                ["50184C"]=1            
            }
        }
    },
    pdfs={
        {
            url="https://steamusercontent-a.akamaihd.net/ugc/12067968375947470579/DB365E3920C00E56B9475D23FA35C81E81BA7839/",
            position={-78.00, 0.50, 30.00},
            scale={4, 1.00, 4}
        }
    },
    logs={
        {
            guid="043571",
            position={-78, 0.59, -28.25},
            scale={4.30, 1.00, 4.30}
        }
    },
    notes={
        executiveBoard={
            title="Executive Board and A.I.M. Interference",
            text="Copy these cards when starting each new scenario, or they will be deleted when the scenario is cleared.",
            position={-96.25, 0.56, -11.75}
        }        
    },
    assets={
        shieldEnvelope={
            guid="575250",
            position={-85.25, 0.60, 6.75},
            scale={2.00, 1.00, 2.00},
            rotation={0, 180, 0},
            locked=true
        },
        aimEnvelope={
            guid="ea1d2b",
            position={-70.75, 0.60, 6.75},
            scale={2.00, 1.00, 2.00},
            rotation={0, 180, 0},
            locked=true
        }        
    }
}