name: Build mod
on:
  push:
    branches:
      - 'ci-dev'
  workflow_dispatch:
jobs:
  push-to-steam:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Validate (WIP)
        run: npm run validate || true
      - name: Create a TTS save
        run: npm run compile
      - name: Save the TTS save as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Mod Save file
          path: |
            dist