name: prod-deploy
on:
  push:
    tags:
      - "v*"
jobs:
  push-to-steam:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install node dependencies
        shell: cmd
        run: npm ci
      - name: Validate (WIP)
        shell: cmd
        run: npm run validate || true
      - name: Create a TTS save
        shell: cmd
        run: npm run compile
      - name: Convert save file to BSON
        shell: cmd
        run: |
          npm run convertToBSON
      - name: steam-workshop-legacy-upload
        shell: cmd
        run: |
          "C:\Program Files (x86)\kpsteam\kpsteam.exe" upload --legacy --app 286160 --item 2824240402 --path ".\dist\MarvelChampionsLCG.bson"