name: prod-deploy
on:
  push:
    tags:
      - "v*"
jobs:
  compile:
    uses: funkymonkeymonk/MarvelChampionsScripted/.github/workflows/compile-mod.yml@main
  tag-stable-release:
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ModSaveFile
          path: ./dist/
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "stable"
          prerelease: false
          title: "Latest Stable Release"
          files: |
            dist/MarvelChampionsLCG.json
  push-to-steam:
    needs: compile
    runs-on: self-hosted
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ModSaveFile
          path: ./dist/
      - name: steam-workshop-legacy-upload
        shell: cmd
        run: |
          "C:\Program Files (x86)\kpsteam\kpsteam.exe" upload --legacy --app 286160 --item 2824240402 --path ".\dist\MarvelChampionsLCG.bson"